name: Ping Web Site

on:
  push:
    branches: [ master ]
  schedule: 
    - cron: '*/10 * * * *' #every 10 minutes
jobs:
  ping:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet tool install Web.Ping -g
    - name: Ping kingston
      run: Web.Ping --host https://www.kingston.com/unitedstates/us
    - name: Ping HyperX
      run: Web.Ping --host https://www.hyperxgaming.com/unitedstates/us
